Repository ActiveState/cli, pull requests merged in 2020-08, with the labels that each got.

#852 Paid tiers were still set to 'privateAllowed=false'
  internal/runners/auth/auth.go
Labels: version: patch

#851 Implemented `state tutorial`
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/tutorial.go
  internal/analytics/analytics.go
  internal/config/config.go
  internal/constants/constants.go
  internal/language/language.go
  internal/runbits/invoke.go
  internal/runners/push/push.go
  internal/runners/tutorial/tutorial.go
  locale/en-us.yaml
  pkg/cmdlets/auth/keypair.go
  pkg/cmdlets/auth/signup.go
Labels: version: minor

#854 Our language installers have a link to the State Tool shortcut
  installers/msi-language/CustomExitDlg.wxs
  installers/msi-language/Product.p.wxs
  installers/msi-language/en-US.wxl
Labels: version: patch

#855 MSI cannot remove directory on uninstall
  installers/msi-language/Uninstall/CustomAction.cs
  installers/msi-language/Uninstall/Uninstall.csproj
Labels: version: patch

#856 only add force flag for symlink sub-command
  installers/msi-language/CustomExitDlg.wxs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#850 Add PPM conversion flow
  cmd/state/internal/cmdtree/ppm.go
  go.sum
  internal/analytics/analytics.go
  internal/constants/constants.go
  internal/runners/ppm/convert.go
  locale/en-us.yaml
Labels: version: patch

#858 Clean up tutorial and PPM conversion UX
  cmd/state/internal/cmdtree/ppm.go
  cmd/state/internal/cmdtree/tutorial.go
  internal/prompt/helpers.go
  internal/runbits/invoke.go
  internal/runners/ppm/convert.go
  internal/runners/ppm/shim.go
  internal/runners/tutorial/tutorial.go
  locale/en-us.yaml
Labels: version: patch

#860 Update version info (license, company)
  internal/constants/constants.go
  internal/runners/state/state.go
  locale/en-us.yaml
Labels: version: patch

#861 Move Project/Build GA Events
  internal/runners/activate/activate.go
  pkg/platform/runtime/download.go
Labels: version: patch

#859 Track installation source
  installers/install.ps1
  installers/install.sh
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
  internal/analytics/analytics.go
Labels: version: patch

#857 add project ID to run-command,activate GA event
  cmd/state/internal/cmdtree/activate.go
  internal/captain/command.go
  internal/runners/activate/activate.go
Labels: version: patch

#863 Rollbar Fix
  internal/analytics/analytics.go
Labels: version: patch

#866 Fix version not updating
  .github/workflows-src/steps.lib.yml
  activestate.yaml
  scripts/version-generator/main.go
Labels: version: patch

#868 Update copy based on Dana's feedback
  internal/runners/ppm/convert.go
  internal/runners/tutorial/tutorial.go
  locale/en-us.yaml
Labels: version: patch

#867 Rollbar install source
  internal/analytics/analytics.go
  internal/config/config.go
  internal/config/instance.go
  internal/logging/rollbar.go
Labels: version: patch

#862 Deprecation file fix
  internal/deprecation/deprecation.go
Labels: version: patch

#869 Remove fmt print from rollbar setup
  internal/logging/rollbar.go
Labels: version: patch

#853 Shim popular PPM commands
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/ppm.go
  cmd/state/internal/cmdtree/tutorial.go
  go.sum
  internal/analytics/analytics.go
  internal/constants/constants.go
  internal/prompt/helpers.go
  internal/runbits/invoke.go
  internal/runners/ppm/convert.go
  internal/runners/ppm/shim.go
  internal/runners/tutorial/tutorial.go
  locale/en-us.yaml
Labels: version: patch

#871 Fix forum url
  internal/constants/constants.go
  internal/runners/ppm/convert.go
  locale/en-us.yaml
Labels: version: patch

#870 Include commit ID in Rollbar logs
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/Preset/CustomAction.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/Rollback/CustomAction.cs
  installers/msi-language/StateCommandExists/CustomAction.cs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/Uninstall/CustomAction.cs
  scripts/msi-installer-builder/main.go
Labels: version: patch

#873 Delete file extensions in MSI on uninstall
  installers/msi-language/ActiveState/FileAssociation.cs
Labels: version: patch

#874 MSI logs only first critical error
  installers/msi-language/ActiveState/Command.cs
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/Preset/CustomAction.cs
  installers/msi-language/Rollback/CustomAction.cs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/Uninstall/CustomAction.cs
Labels: version: patch

#877 Wrap long output lines
  go.mod
  go.sum
  internal/output/plain.go
  vendor/github.com/mitchellh/go-wordwrap/LICENSE.md
  vendor/github.com/mitchellh/go-wordwrap/README.md
  vendor/github.com/mitchellh/go-wordwrap/go.mod
  vendor/github.com/mitchellh/go-wordwrap/wordwrap.go
  vendor/modules.txt
Labels: version: patch

#875 Win32 state tool installation
  .github/workflows-src/jobs.lib.yml
  .github/workflows-src/steps.lib.yml
  .github/workflows/build.yml
  activestate.yaml
  installers/install.ps1
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#876 MSI installs VSCode extension
  installers/msi-language/CustomExitDlg.wxs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateCommandExists/CustomAction.cs
  installers/msi-language/en-US.wxl
Labels: version: patch

#872 Ensure artifact files are deleted and the deletions aren't cached
  internal/fileutils/fileutils.go
  pkg/platform/runtime/alternative.go
  pkg/platform/runtime/camel.go
  pkg/platform/runtime/installer.go
Labels: version: patch

#878 Add language to as.yaml template
  locale/en-us.yaml
  pkg/projectfile/projectfile.go
Labels: version: patch

#888 Prevent concurrent map writes
  pkg/projectfile/projectfile.go
Labels: version: patch

#889 State pacakges --output=json has json output
  internal/runners/packages/list.go
  internal/runners/packages/search.go
  internal/runners/packages/table.go
  locale/en-us.yaml
Labels: version: patch

#887 Fix State Tool wizard launch
  installers/msi-language/Product.p.wxs
Labels: version: patch

#886 Require .Net 4.5.2
  installers/msi-language/Deploy.wixproj
  installers/msi-language/Product.p.wxs
Labels: version: patch

#890 Retry downloads
  go.mod
  go.sum
  internal/download/get.go
  vendor/github.com/hashicorp/go-cleanhttp/LICENSE
  vendor/github.com/hashicorp/go-cleanhttp/README.md
  vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go
  vendor/github.com/hashicorp/go-cleanhttp/doc.go
  vendor/github.com/hashicorp/go-cleanhttp/go.mod
  vendor/github.com/hashicorp/go-cleanhttp/handlers.go
  vendor/github.com/hashicorp/go-retryablehttp/.gitignore
  vendor/github.com/hashicorp/go-retryablehttp/LICENSE
  vendor/github.com/hashicorp/go-retryablehttp/Makefile
  vendor/github.com/hashicorp/go-retryablehttp/README.md
  vendor/github.com/hashicorp/go-retryablehttp/client.go
  vendor/github.com/hashicorp/go-retryablehttp/go.mod
  vendor/github.com/hashicorp/go-retryablehttp/go.sum
  vendor/github.com/hashicorp/go-retryablehttp/roundtripper.go
  vendor/modules.txt
Labels: version: patch

#891 Update whitespace and skip-intro
  cmd/state/internal/cmdtree/tutorial.go
  locale/en-us.yaml
Labels: version: patch

#892 Fix cutoff tutorial text
  cmd/state/internal/cmdtree/tutorial.go
Labels: version: patch

#893 Add custom fatal error dialog to msi-lang
  activestate.yaml
  installers/msi-language/CustomFatalError.wxs
  installers/msi-language/Deploy.wixproj
  installers/msi-language/Product.p.wxs
  installers/msi-language/en-US.wxl
Labels: version: minor

#895 Fix locale error
  internal/locale/errors.go
  internal/runners/export/config/filter.go
  locale/en-us.yaml
Labels: version: patch

#894 Send GA pixel in language MSI
  installers/msi-language/Deploy.sln
  installers/msi-language/Deploy.wixproj
  installers/msi-language/GAPixel/CustomAction.config
  installers/msi-language/GAPixel/GAPixel.csproj
  installers/msi-language/GAPixel/GAPixelCA.cs
  installers/msi-language/GAPixel/Properties/AssemblyInfo.cs
  installers/msi-language/Product.p.wxs
Labels: version: patch

#897 Report MSI stages to GA
  installers/msi-language/ActiveState/ActiveState.csproj
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/ActiveState/packages.config
  installers/msi-language/CustomExitDlg.wxs
  installers/msi-language/GAPixel/GAPixelCA.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/packages/GoogleAnalyticsTracker.Core.4.5.0/.signature.p7s
  installers/msi-language/packages/GoogleAnalyticsTracker.Core.4.5.0/GoogleAnalyticsTracker.Core.4.5.0.nupkg
  installers/msi-language/packages/GoogleAnalyticsTracker.Core.4.5.0/lib/portable45-net45+win8+wpa81/GoogleAnalyticsTracker.Core.dll
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/.signature.p7s
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/GoogleAnalyticsTracker.Simple.4.5.0.nupkg
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/lib/portable45-net45+win8+wpa81/GoogleAnalyticsTracker.Simple.dll
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/src/EventViewTrackerExtensions.cs
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/src/PageViewTrackerExtensions.cs
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/src/Properties/AssemblyInfo.cs
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/src/Properties/SharedAssemblyInfo.cs
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/src/ScreenviewTrackerExtension.cs
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/src/SimpleTracker.cs
  installers/msi-language/packages/GoogleAnalyticsTracker.Simple.4.5.0/src/SimpleTrackerEnvironment.cs
Labels: version: patch

#881 Added "jobs" to activestate.yaml and `state export github-actions
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/export.go
  internal/runners/export/ghactions/ghactions.go
  internal/runners/export/ghactions/types.go
  pkg/project/project.go
  pkg/projectfile/projectfile.go
Labels: version: minor

#903 Write compatiblity warning for windows < 10
  cmd/state/main.go
  locale/en-us.yaml
Labels: version: patch

#901 State tutorial locale fix
  internal/locale/locale.go
Labels: version: patch

#904 Add custom dimension for GA events
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#905 Integration Tests
  activestate.yaml
  locale/en-us.yaml
Labels: run integration tests, version: patch

#907 Fix UUID errcheck
  internal/constraints/constraints_test.go
  pkg/projectfile/projectfile.go
Labels: version: patch

#910 Record datetime to rollbar version
  internal/constants/constants.go
  internal/constants/preprocess/preprocess.go
  internal/logging/rollbar.go
Labels: version: patch

#908 Run critical integration tests for every PR
  .github/workflows-src/build.yml
  .github/workflows-src/jobs.lib.yml
  .github/workflows-src/steps.lib.yml
  .github/workflows/build.yml
Labels: version: patch

#912 MSI Rollbar reports fix
  installers/msi-language/ActiveState/Rollbar.cs
Labels: version: patch

#913 Don't need int tests on master, just on PRs
  .github/workflows-src/build.yml
  .github/workflows/build.yml
Labels: version: patch

#911 Fix termwidth not being calculated properly under cmd.exe
  internal/output/plain.go
  internal/runbits/invoke.go
Labels: version: patch

#915 Fix tutorial window
  installers/msi-language/Product.p.wxs
Labels: version: patch

#914 Ensure rollbar finishes before exiting
  cmd/state/main.go
Labels: version: patch

#916 Use short revision hash for rollbar version
  internal/logging/rollbar.go
Labels: version: patch

#917 Remove works from MSI menu
  installers/msi-language/Product.p.wxs
Labels: version: patch

#918 Do not remove existing state tool executable
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#921 Improve move files logging
  pkg/platform/runtime/camel.go
Labels: version: patch

#920 MSI logging sent to rollbar
  installers/msi-language/ActiveState/ActiveState.csproj
  installers/msi-language/ActiveState/Command.cs
  installers/msi-language/ActiveState/Logging.cs
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/Preset/CustomAction.cs
  installers/msi-language/Rollback/CustomAction.cs
  installers/msi-language/S3Pixel/S3Pixel.cs
  installers/msi-language/StateCommandExists/CustomAction.cs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/Uninstall/CustomAction.cs
Labels: version: patch

#922 Fix short rollbar titles
  installers/msi-language/ActiveState/Command.cs
Labels: version: patch

#923 Add retries to graphql calls
  go.mod
  go.sum
  pkg/platform/api/graphql/graphql.go
Labels: version: patch

#924 Retry downloads of state tool artifacts
  installers/msi-language/ActiveState/ActiveState.csproj
  installers/msi-language/ActiveState/Retry.cs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#926 Don't report project not found errors to rollbar
  pkg/platform/model/projects.go
Labels: version: patch

#925 Check for clean installation directory
  installers/msi-language/.editorconfig
  installers/msi-language/CustomExitDlg.wxs
  installers/msi-language/CustomFatalError.wxs
  installers/msi-language/Deploy.sln
  installers/msi-language/Deploy.wixproj
  installers/msi-language/Login.wxs
  installers/msi-language/NonEmptyDirDlg.wxs
  installers/msi-language/PrivacyConsentDlg.wxs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/en-US.wxl
  internal/runners/deploy/deploy.go
  test/integration/deploy_int_test.go
Labels: version: patch

#927 Install source fix
  installers/msi-language/ActiveState/Command.cs
Labels: version: patch

#928 MSI run state tool verbose
  installers/msi-language/ActiveState/Command.cs
Labels: version: patch

#930 Silence progressbar
  installers/msi-language/ActiveState/Command.cs
  pkg/platform/runtime/installer.go
Labels: version: patch

#929 Use file modification time as source of truth for update check
  assets/ppm/ppm.bat
  assets/ppm/ppm.sh
  cmd/state/autoupdate.go
  cmd/state/autoupdate_test.go
  internal/strutils/strutils.go
  internal/testhelpers/e2e/session.go
  internal/testhelpers/e2e/spawn.go
  internal/updater/check.go
  internal/updater/check_test.go
  pkg/platform/runtime/installer.go
  pkg/platform/runtime/internal_test.go
  test/integration/update_int_test.go
Labels: version: patch

#931 Funnel logging to retryhttp library
  internal/download/get.go
  internal/logging/defaults.go
  internal/logging/logging.go
  internal/logging/logging_test.go
  pkg/platform/api/graphql/graphql.go
Labels: version: patch

#785 Added language flag to `state packages import`
  cmd/state/internal/cmdtree/packages.go
  internal/runners/packages/import.go
  pkg/platform/api/reqsimport/reqsimport.go
Labels: version: minor

#933 Infer the language instead of requiring the user to input it
  cmd/state/internal/cmdtree/packages.go
  internal/runners/packages/import.go
  internal/runners/packages/list.go
  pkg/platform/model/checkpoints.go
Labels: version: patch

#932 Add http retry to inventory and headchef calls (and centralize retry setup)
  internal/download/get.go
  internal/retryhttp/client.go
  pkg/platform/api/graphql/graphql.go
  pkg/platform/api/headchef/headchef.go
  pkg/platform/model/inventory.go
  pkg/platform/model/recipe.go
Labels: version: patch

#909 Ensure state cmd avialable as alias if not on path
  assets/shells/bashrc.sh
  assets/shells/config.bat
  assets/shells/fishrc.fish
  assets/shells/tcsh.sh
  assets/shells/zshrc.sh
  internal/fileutils/fileutils.go
  internal/osutils/osutils.go
  internal/subshell/sscommon/rcfile.go
  internal/testhelpers/e2e/session.go
  test/integration/activate_int_test.go
Labels: version: patch

#934 Fix bash script calls from cmd.exe
  internal/subshell/sscommon/sscommon.go
Labels: version: patch

#936 Comment state tool wizard checkbox
  installers/msi-language/CustomExitDlg.wxs
  installers/msi-language/Product.p.wxs
Labels: version: patch

#935 Sync the pixel events
  installers/msi-language/Product.p.wxs
Labels: version: patch

#939 Send stage events to S3
  installers/msi-language/.editorconfig
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/Deploy.sln
  installers/msi-language/Deploy.wixproj
  installers/msi-language/Product.p.wxs
  installers/msi-language/S3Pixel/CustomAction.config
  installers/msi-language/S3Pixel/Properties/AssemblyInfo.cs
  installers/msi-language/S3Pixel/S3Pixel.cs
  installers/msi-language/S3Pixel/S3Pixel.csproj
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#940 Enhance rollbar logging 174555634
  installers/msi-language/ActiveState/Command.cs
  installers/msi-language/ActiveState/Logging.cs
  installers/msi-language/ActiveState/Retry.cs
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/Preset/CustomAction.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/Rollback/CustomAction.cs
  installers/msi-language/StateCommandExists/CustomAction.cs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/Uninstall/CustomAction.cs
Labels: version: patch
