Repository ActiveState/cli, pull requests merged in 2020-10, with the labels that each got.

#1006 Ensure activate uses project.GetSafe by default
  internal/runners/activate/activate.go
Labels: version: patch

#1005 compute cid based on MAC address and Windows Product Key
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/GAPixel/GAPixelCA.cs
Labels: version: patch

#1010 Refactor projectfile detection to fix bugs and be less error prone
  internal/runners/activate/activate.go
  internal/runners/activate/activate_test.go
  pkg/projectfile/projectfile.go
Labels: version: patch

#1009 Make ps1 installer success msg more general
  installers/install.ps1
Labels: version: patch

#1007 First activate
  internal/subshell/sscommon/rcfile.go
  test/integration/events_int_test.go
Labels: version: patch

#1014 Update commit ID, and account for non-alternate builds
  internal/runners/packages/packages.go
  locale/en-us.yaml
  pkg/platform/model/inventory.go
Labels: version: patch

#1011 State packages bundles support
  internal/runners/packages/packages.go
  internal/runners/packages/remove.go
  pkg/platform/model/checkpoints.go
  pkg/platform/model/inventory.go
  pkg/platform/model/vcs.go
  pkg/platform/model/vcs_test.go
Labels: version: patch

#1017 Update Mono API types
  pkg/platform/api/mono/mono_client/projects/add_branch_parameters.go
  pkg/platform/api/mono/mono_client/projects/add_branch_responses.go
  pkg/platform/api/mono/mono_client/projects/projects_client.go
  pkg/platform/api/mono/mono_client/version_control/delete_branch_parameters.go
  pkg/platform/api/mono/mono_client/version_control/delete_branch_responses.go
  pkg/platform/api/mono/mono_client/version_control/get_checkpoint_responses.go
  pkg/platform/api/mono/mono_client/version_control/get_commit_history_responses.go
  pkg/platform/api/mono/mono_client/version_control/get_commit_responses.go
  pkg/platform/api/mono/mono_client/version_control/get_order_from_checkpoint_parameters.go
  pkg/platform/api/mono/mono_client/version_control/get_order_from_checkpoint_responses.go
  pkg/platform/api/mono/mono_client/version_control/get_order_responses.go
  pkg/platform/api/mono/mono_client/version_control/get_revert_commit_parameters.go
  pkg/platform/api/mono/mono_client/version_control/get_revert_commit_responses.go
  pkg/platform/api/mono/mono_client/version_control/merge_branch_parameters.go
  pkg/platform/api/mono/mono_client/version_control/merge_branch_responses.go
  pkg/platform/api/mono/mono_client/version_control/update_branch_responses.go
  pkg/platform/api/mono/mono_client/version_control/version_control_client.go
  pkg/platform/api/mono/mono_models/branch.go
  pkg/platform/api/mono/mono_models/branch_editable.go
  pkg/platform/api/mono/mono_models/branch_merge_strategies.go
  pkg/platform/api/mono/mono_models/commit.go
  pkg/platform/api/mono/mono_models/order.go
  pkg/platform/api/mono/mono_models/order_annotations.go
  pkg/platform/api/mono/mono_models/order_info.go
  pkg/platform/api/mono/mono_models/project_editable.go
  pkg/platform/api/mono/mono_models/requirement_key.go
  pkg/platform/api/mono/mono_models/user.go
  pkg/platform/model/projects.go
Labels: version: patch

#1004 State shim
  cmd/state/autoupdate.go
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/shim.go
  cmd/state/internal/cmdtree/update.go
  cmd/state/main.go
  internal/captain/command.go
  internal/runners/run/run.go
  internal/runners/shim/shim.go
  locale/en-us.yaml
  test/integration/shim_int_test.go
Labels: version: patch

#1012 Start commit-only ASY project handling
  internal/constants/constants.go
  internal/runners/activate/activation.go
  locale/en-us.yaml
  pkg/platform/runtime/download.go
  pkg/project/project.go
  pkg/project/project_internal_test.go
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
  test/integration/activate_int_test.go
Labels: version: patch

#1019 Support state protocol
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/protocol.go
  internal/osutils/env.go
  internal/osutils/env_lin_mac.go
  internal/osutils/env_windows.go
  internal/runners/prepare/prepare.go
  internal/runners/protocol/protocol.go
  internal/subshell/cmd/cmd.go
  internal/subshell/cmd/env.go
  internal/subshell/cmd/env_test.go
  locale/en-us.yaml
Labels: version: patch

#1015 Support extended support Python versions
  internal/language/language.go
  internal/language/language_test.go
Labels: version: patch

#1021 install.sh does not require State Tool to be on PATH if --activate
  installers/install.sh
Labels: version: patch

#1022 install.sh does not run `set -i`
  installers/install.sh
Labels: version: patch

#1016 Add headless notices at end of cmd exec
  internal/headless/headless.go
  internal/runners/activate/activate.go
  internal/runners/activate/activation.go
  internal/runners/packages/add.go
  internal/runners/packages/import.go
  internal/runners/packages/remove.go
  internal/runners/packages/update.go
  internal/runners/run/run.go
  locale/en-us.yaml
  pkg/projectfile/projectfile.go
Labels: version: patch

#1026 Stop reporting cancellations to rollbar
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#1027 remove explicit colors in favor of semantic formatters
  internal/output/color.go
  internal/output/color_test.go
  internal/output/plain.go
  internal/runners/run/run.go
  internal/runners/tutorial/tutorial.go
  locale/en-us.yaml
Labels: version: patch

#1024 Add title mechanism to captain command
  cmd/state/internal/cmdtree/activate.go
  cmd/state/internal/cmdtree/auth.go
  cmd/state/internal/cmdtree/clean.go
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/deploy.go
  cmd/state/internal/cmdtree/events.go
  cmd/state/internal/cmdtree/export.go
  cmd/state/internal/cmdtree/fork.go
  cmd/state/internal/cmdtree/history.go
  cmd/state/internal/cmdtree/init.go
  cmd/state/internal/cmdtree/invite.go
  cmd/state/internal/cmdtree/languages.go
  cmd/state/internal/cmdtree/organizations.go
  cmd/state/internal/cmdtree/packages.go
  cmd/state/internal/cmdtree/platforms.go
  cmd/state/internal/cmdtree/prepare.go
  cmd/state/internal/cmdtree/projects.go
  cmd/state/internal/cmdtree/protocol.go
  cmd/state/internal/cmdtree/pull.go
  cmd/state/internal/cmdtree/push.go
  cmd/state/internal/cmdtree/run.go
  cmd/state/internal/cmdtree/scripts.go
  cmd/state/internal/cmdtree/shim.go
  cmd/state/internal/cmdtree/show.go
  cmd/state/internal/cmdtree/tutorial.go
  cmd/state/internal/cmdtree/update.go
  internal/captain/command.go
  internal/output/mediator.go
  internal/output/output.go
  internal/output/plain.go
  internal/output/txtstyle/title.go
  internal/output/txtstyle/title_test.go
Labels: version: patch

#1013 State packages add/update/remove can enter headless-commit state
  internal/runners/activate/activate.go
  internal/runners/packages/add.go
  internal/runners/packages/import.go
  internal/runners/packages/packages.go
  internal/runners/packages/remove.go
  internal/runners/packages/update.go
  internal/runners/pull/pull.go
  internal/runners/push/push.go
  internal/virtualenvironment/virtualenvironment.go
  locale/en-us.yaml
  pkg/cmdlets/auth/login.go
  pkg/cmdlets/commands/commands.go
  pkg/platform/model/vcs.go
  pkg/project/namespace_test.go
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
  pkg/projectfile/testdata/activestate.yaml
  test/integration/package_int_test.go
Labels: version: minor

#1025 Table output
  go.mod
  internal/output/plain.go
  internal/output/plain_test.go
  internal/runners/events/events.go
  internal/runners/platforms/platforms.go
  internal/runners/scripts/scripts.go
  internal/runners/scripts/scripts_test.go
  internal/tabulate/tabulate.go
  internal/tabulate/utils.go
Labels: version: patch

#1030 Don't fail if bundle search errors out because it's not widely available yet
  pkg/platform/model/inventory.go
Labels: version: patch

#1031 Fix packages search panic
  internal/runners/packages/search.go
Labels: version: patch

#1032 Fix shim panic
  internal/runners/shim/shim.go
  internal/virtualenvironment/virtualenvironment.go
Labels: version: patch

#896 Scripts support multiple languages
  internal/runners/run/run.go
  internal/runners/run/run_test.go
  internal/runners/scripts/edit.go
  pkg/project/expander.go
  pkg/project/expander_test.go
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
  test/integration/komodo_int_test.go
  test/integration/run_int_test.go
Labels: version: patch

#1034 Improved User Experience
  assets/shells/bashrc.sh
  assets/shells/config.bat
  assets/shells/fishrc.fish
  assets/shells/tcsh.sh
  assets/shells/zshrc.sh
  cmd/state/autoupdate.go
  cmd/state/errors.go
  cmd/state/forward.go
  cmd/state/main.go
  cmd/state/main_test.go
  go.mod
  go.sum
  internal/colorize/color_test.go
  internal/colorize/colorize.go
  internal/errs/errs.go
  internal/locale/errors.go
  internal/output/color.go
  internal/output/colorstyle/ansi.go
  internal/output/colorstyle/colorstyle.go
  internal/output/colorstyle/console_windows.go
  internal/output/colorstyle/license.txt
  internal/output/plain.go
  internal/output/presets.go
  internal/output/txtstyle/title.go
  internal/output/txtstyle/title_test.go
  internal/runbits/invoke.go
  internal/runbits/runtimemsg.go
  internal/runners/activate/activate.go
  internal/runners/activate/activation.go
  internal/runners/auth/auth.go
  internal/runners/auth/logout.go
  internal/runners/deploy/deploy.go
  internal/runners/languages/languages.go
  internal/runners/packages/packages.go
  internal/runners/prepare/prepare.go
  internal/runners/run/run.go
  internal/subshell/sscommon/rcfile.go
  internal/updater/updater.go
  internal/updater/updater_test.go
  locale/en-us.yaml
  pkg/cmdlets/checker/checker.go
  pkg/platform/runtime/installer.go
  test/integration/activate_int_test.go
  test/integration/push_int_test.go
  vendor/github.com/ActiveState/go-colortext/.gitignore
  vendor/github.com/ActiveState/go-colortext/README.md
  vendor/github.com/ActiveState/go-colortext/ct.go
  vendor/github.com/ActiveState/go-colortext/ct_ansi.go
  vendor/github.com/ActiveState/go-colortext/ct_win.go
  vendor/modules.txt
Labels: version: minor

#1035 remove titles from internal commands
  cmd/state/internal/cmdtree/prepare.go
  cmd/state/internal/cmdtree/protocol.go
  cmd/state/internal/cmdtree/shim.go
Labels: version: patch

#1039 Reorganize pkgs cmds
  cmd/state/internal/cmdtree/clean.go
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/languages.go
  cmd/state/internal/cmdtree/packages.go
  internal/captain/command.go
  internal/failures/failures.go
  internal/runners/languages/languages.go
  internal/runners/packages/add.go
  internal/runners/packages/install.go
  internal/runners/packages/search.go
  internal/runners/packages/uninstall.go
  internal/runners/packages/update.go
  internal/runners/ppm/shim.go
  internal/runners/show/show.go
  locale/en-us.yaml
  pkg/platform/model/checkpoints.go
  pkg/platform/model/projects.go
  test/integration/package_int_test.go
Labels: version: minor

#1041 fix regression: nested activations
  internal/runners/activate/activate.go
  internal/virtualenvironment/virtualenvironment.go
  internal/virtualenvironment/virtualenvironment_test.go
  test/integration/activate_int_test.go
Labels: run integration tests, run-int-test-only:run, version: patch

#1038 UX Improvements
  assets/activestate.yaml.editor.tpl
  assets/activestate.yaml.perl.tpl
  assets/activestate.yaml.python.tpl
  assets/shells/bashrc.sh
  assets/shells/config.bat
  assets/shells/fishrc.fish
  assets/shells/zshrc.sh
  cmd/state/errors.go
  cmd/state/internal/cmdtree/activate.go
  cmd/state/internal/cmdtree/run.go
  cmd/state/main.go
  installers/install.ps1
  installers/install.sh
  internal/errs/errs.go
  internal/failures/failures.go
  internal/language/language.go
  internal/locale/errors.go
  internal/output/presets.go
  internal/output/txtstyle/title.go
  internal/output/txtstyle/title_test.go
  internal/prompt/helpers.go
  internal/prompt/mock/mock.go
  internal/prompt/overrides.go
  internal/prompt/prompt.go
  internal/runners/activate/activate.go
  internal/runners/activate/namespace.go
  internal/runners/clean/cache.go
  internal/runners/clean/config.go
  internal/runners/clean/uninstall.go
  internal/runners/clean/uninstall_test.go
  internal/runners/fork/fork.go
  internal/runners/initialize/init.go
  internal/runners/invite/invite.go
  internal/runners/packages/import.go
  internal/runners/packages/packages.go
  internal/runners/ppm/convert.go
  internal/runners/run/run.go
  internal/runners/run/run_test.go
  internal/runners/scripts/edit.go
  internal/runners/tutorial/tutorial.go
  internal/runners/update/update.go
  internal/subshell/sscommon/rcfile.go
  locale/en-us.yaml
  pkg/cmdlets/auth/keypair.go
  pkg/cmdlets/auth/login.go
  pkg/cmdlets/auth/signup.go
  pkg/cmdlets/git/git_test.go
  pkg/cmdlets/git/mock/mock.go
  pkg/project/secrets.go
  pkg/projectfile/create_test.go
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
  test/integration/activate_int_test.go
  test/integration/init_int_test.go
  test/integration/komodo_int_test.go
  test/integration/shared_int_test.go
Labels: version: patch

#1042 Expand top level yaml fields
  pkg/project/expander.go
  pkg/project/expander_test.go
  pkg/project/project.go
  pkg/project/prompting_expander_test.go
  pkg/project/registry.go
  pkg/project/registry_test.go
  pkg/project/secrets.go
  pkg/project/secrets_test.go
Labels: version: patch

#1044 WIP: Remove deprecated project attributes
  locale/en-us.yaml
  pkg/project/project_test.go
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
Labels: version: patch

#1046 update termtest to 0.6.1
  go.mod
  go.sum
  vendor/github.com/ActiveState/termtest/go.mod
  vendor/github.com/ActiveState/termtest/go.sum
  vendor/golang.org/x/sys/cpu/cpu_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_netbsd_arm64.go
  vendor/golang.org/x/sys/cpu/cpu_other_arm64.go
  vendor/golang.org/x/sys/unix/syscall.go
  vendor/golang.org/x/sys/windows/registry/zsyscall_windows.go
  vendor/golang.org/x/sys/windows/syscall.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: version: patch

#1047 State auth signup fails if already authenticated
  pkg/cmdlets/auth/signup.go
Labels: version: patch

#1048 Remove only the language field on push
  internal/runners/push/push.go
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
Labels: run integration tests, run-int-test-only:push, version: patch

#1040 Reorganize help output
  assets/usage.tpl
  cmd/state/internal/cmdtree/activate.go
  cmd/state/internal/cmdtree/auth.go
  cmd/state/internal/cmdtree/clean.go
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/deploy.go
  cmd/state/internal/cmdtree/events.go
  cmd/state/internal/cmdtree/export.go
  cmd/state/internal/cmdtree/fork.go
  cmd/state/internal/cmdtree/history.go
  cmd/state/internal/cmdtree/init.go
  cmd/state/internal/cmdtree/invite.go
  cmd/state/internal/cmdtree/languages.go
  cmd/state/internal/cmdtree/organizations.go
  cmd/state/internal/cmdtree/packages.go
  cmd/state/internal/cmdtree/platforms.go
  cmd/state/internal/cmdtree/projects.go
  cmd/state/internal/cmdtree/pull.go
  cmd/state/internal/cmdtree/push.go
  cmd/state/internal/cmdtree/run.go
  cmd/state/internal/cmdtree/scripts.go
  cmd/state/internal/cmdtree/shim.go
  cmd/state/internal/cmdtree/show.go
  cmd/state/internal/cmdtree/tutorial.go
  cmd/state/internal/cmdtree/update.go
  internal/captain/command.go
  internal/locale/locale_test.go
  locale/en-us.yaml
  pkg/cmdlets/commands/commands.go
Labels: version: patch

#1051 Fix `state run` not working with batch
  internal/exeutils/exeutils_unix.go
  internal/exeutils/exeutils_windows.go
  internal/language/language.go
  internal/language/language_test.go
  internal/runners/run/run.go
Labels: run-int-test-only:run

#1054 Fix not working with batch
  internal/language/language_test.go
  readme.md
Labels: version: patch

#1058 Fix activation --default failing if runtime wasn't already pulled in
  internal/runners/activate/activate.go
  internal/runners/activate/activation.go
Labels: version: patch

#1059 Fix project field depending on specific hostname
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
Labels: version: patch

#1060 Fix perl scripts can't be ran
  internal/subshell/sscommon/sscommon.go
Labels: version: patch

#1056 UX Improvements
  assets/shells/config.bat
  internal/colorize/colorize.go
  internal/errs/errs.go
  internal/failures/failures.go
  internal/output/colorstyle/console_windows.go
  internal/prompt/cmd/test.go
  internal/prompt/helpers.go
  internal/prompt/helpers_test.go
  internal/prompt/overrides.go
  internal/prompt/prompt.go
  internal/runners/deploy/deploy.go
  internal/runners/run/run.go
  internal/subshell/cmd/cmd.go
  internal/subshell/sscommon/rcfile.go
  locale/en-us.yaml
  pkg/cmdlets/git/git.go
  pkg/platform/model/vcs.go
  pkg/project/expander.go
  pkg/project/expander_test.go
Labels: version: patch

#1063 State shim should not call itself recursively
  assets/shim/shim.bat
  assets/shim/shim.sh
  cmd/state/internal/cmdtree/shim.go
  internal/constants/constants.go
  internal/globaldefault/default.go
  internal/runners/shim/shim.go
Labels: version: patch

#1064 state activate --default integration tests pass again
  internal/testhelpers/e2e/dirs.go
  internal/testhelpers/e2e/session.go
  locale/en-us.yaml
  test/integration/activate_int_test.go
Labels: run integration tests, run-int-test-only:activate, version: patch

#1055 State revert
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/revert.go
  internal/runners/history/history.go
  internal/runners/history/history_test.go
  internal/runners/packages/import.go
  internal/runners/revert/revert.go
  internal/testhelpers/tagsuite/tagsuite.go
  locale/en-us.yaml
  pkg/cmdlets/commit/commit.go
  pkg/platform/model/vcs.go
  test/integration/package_int_test.go
Labels: run integration tests, run-int-test-only:revert, version: patch

#1062 Update state platforms add argument
  cmd/state/internal/cmdtree/platforms.go
  internal/runners/platforms/platforms.go
  locale/en-us.yaml
  pkg/platform/model/checkpoints.go
  test/integration/platforms_int_test.go
Labels: run integration tests, run-int-test-only:platforms, version: patch

#1066 add instrumentation for Carlisle's journey
  cmd/state/errors.go
  internal/analytics/analytics.go
  internal/captain/command.go
  internal/captain/errors.go
  internal/errs/unwrap.go
  internal/failures/failures.go
  internal/subshell/sscommon/sscommon.go
Labels: version: patch
