Repository ActiveState/cli, pull requests merged in 2020-09, with the labels that each got.

#938 Avoid rollbar logs for already updating tool
  internal/osutils/pidlock.go
  internal/osutils/pidlock_test.go
  internal/updater/updater.go
Labels: version: patch

#937 Don't try to list scripts if we aren't in a project
  internal/runners/scripts/scripts.go
Labels: version: patch

#941 Add installed apps and running processes to rollbar
  installers/msi-language/ActiveState/ActiveState.csproj
  installers/msi-language/ActiveState/Logging.cs
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/ActiveState/UserEnvironment.cs
  installers/msi-language/Product.p.wxs
Labels: version: patch

#943 Custom network error text
  installers/msi-language/CustomFatalError.wxs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/en-US.wxl
Labels: version: patch

#944 Send user network finish event
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#945 send tracking events synchronously only
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#946 Exit with code 11 on user network issues
  go.mod
  internal/condition/condition.go
  internal/download/get.go
  internal/retryhttp/client.go
  internal/retryhttp/client_test.go
Labels: version: patch

#942 Update msi rollbar version format
  installers/msi-language/Preset/CustomAction.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/Rollback/CustomAction.cs
  installers/msi-language/StateCommandExists/CustomAction.cs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/Uninstall/CustomAction.cs
  scripts/msi-installer-builder/main.go
Labels: version: patch

#950 Retry underlying VersionControl.GetOrder requests
  pkg/platform/model/vcs.go
Labels: version: patch

#948 Handle SessionID edge cases
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#953 Send UI Level with Start event
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#952 Catch and handle rollbar exceptions
  installers/msi-language/ActiveState/Rollbar.cs
Labels: version: patch

#954 Ensure we log the status code when network error occurs
  internal/download/get.go
Labels: version: patch

#951 Detect network issues from state commands
  installers/msi-language/ActiveState/ActiveState.csproj
  installers/msi-language/ActiveState/Command.cs
  installers/msi-language/ActiveState/Network.cs
  installers/msi-language/CustomFatalError.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#956 Report installation mode to Rollbar
  installers/msi-language/ActiveState/Logging.cs
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/Status/CustomAction.cs
Labels: version: patch

#957 update state packages test
  internal/runners/packages/import.go
  test/integration/package_int_test.go
Labels: run integration tests, version: patch

#955 Forward CommitID to MSI
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
  scripts/msi-installer-builder/main.go
Labels: version: patch

#947 Allow user-defined commit id in activate checkout and deploy
  internal/runners/activate/activate_test.go
  internal/runners/activate/checkout.go
  internal/runners/deploy/deploy.go
  internal/runners/deploy/deploy_test.go
  internal/runners/fork/fork.go
  locale/en-us.yaml
  pkg/project/namespace.go
  pkg/project/namespace_test.go
  test/integration/activate_int_test.go
Labels: version: patch

#960 Add CommitID to all deploy sub-commands
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#961 Revert "state deploy checks for clean target directory"
  internal/runners/deploy/deploy.go
  test/integration/deploy_int_test.go
Labels: version: patch

#962 `trialRename` tests a more relevant use-case (moving dir with file, rather than just file)
  internal/fileutils/fileutils.go
Labels: version: patch

#964 Produce error code 11 on DNS errors
  internal/retryhttp/client.go
  internal/retryhttp/roundtripper.go
Labels: version: patch

#965 Drop trialRename
  internal/fileutils/fileutils.go
Labels: version: patch

#966 Capture wsarecv errors as user network errors (exit code 11)
  internal/retryhttp/client.go
Labels: version: patch

#968 Fix l10n func usage in auth cmdlet
  pkg/cmdlets/auth/signup.go
Labels: version: patch

#969 Fix nil pointer panic
  internal/download/get.go
Labels: version: patch

#970 Path error dialog
  installers/msi-language/ActiveState/ActiveState.csproj
  installers/msi-language/ActiveState/Command.cs
  installers/msi-language/ActiveState/Error.cs
  installers/msi-language/ActiveState/Network.cs
  installers/msi-language/CustomNetworkError.wxs
  installers/msi-language/CustomSecurityError.wxs
  installers/msi-language/Deploy.wixproj
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/en-US.wxl
Labels: version: patch

#967 We support relocation of artifacts produced by the alternative builder
  locale/en-us.yaml
  pkg/platform/runtime/alternative.go
  pkg/platform/runtime/envdef/constants.go
  pkg/platform/runtime/envdef/environment.go
  pkg/platform/runtime/envdef/environment_test.go
  pkg/platform/runtime/envdef/file_transform.go
  pkg/platform/runtime/envdef/file_transform_test.go
  test/integration/alternative_int_test.go
Labels: version: patch

#971 Custom Perl MSI shortcuts
  .github/workflows-src/steps.lib.yml
  installers/msi-language/Preset/CustomAction.cs
  scripts/msi-installer-builder/main.go
Labels: version: patch

#972 Add country to MSI Rollbar reports
  installers/msi-language/ActiveState/Logging.cs
  installers/msi-language/ActiveState/Rollbar.cs
Labels: version: patch

#975 Retry download body reads up to 3 times
  internal/download/get.go
Labels: version: patch

#976 Ensure user_network event is properly captured
  installers/msi-language/ActiveState/ActiveState.csproj
  installers/msi-language/ActiveState/Logging.cs
  installers/msi-language/ActiveState/TimeoutWebClient.cs
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/StateDeploy/CustomAction.cs
  internal/retryhttp/client.go
Labels: version: patch

#977 State Tool downloaded from CDN
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#979 apply transformations in correct directory
  pkg/platform/runtime/alternative.go
Labels: version: patch

#978 Report cancellation reason to GA/S3
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/CustomUserExitDialog.wxs
  installers/msi-language/Deploy.wixproj
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#983 Report premature exits to rollbar
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#984 Retry s3 pixel downloads up to 3 times
  installers/msi-language/ActiveState/Tracker.cs
Labels: version: patch

#986 setting UILevel as third dimenstion in GA tracking
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#985 Capture cancellation dialogs when cancel button was not pressed
  installers/msi-language/Product.p.wxs
Labels: version: patch

#980 Fake progress bar during installation
  installers/msi-language/ActiveState/Command.cs
  installers/msi-language/StateDeploy/CustomAction.cs
  installers/msi-language/Status/CustomAction.cs
Labels: version: patch

#988 enforce ascii encoding when writing to installsource.txt on Windows
  installers/install.ps1
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#987 Handle HTTP erros when downloading TOS
  pkg/cmdlets/auth/signup.go
Labels: version: patch

#990 Get rid of async warning
  installers/msi-language/ActiveState/Tracker.cs
Labels: version: patch

#981 Ensure solveorder retries
  internal/retryhttp/client.go
  internal/retryhttp/client_test.go
  internal/testhelpers/srvstatus/srvstatus.go
  pkg/platform/model/recipe.go
Labels: version: patch

#989 Do not report cmd string when running auth commands
  installers/msi-language/ActiveState/Command.cs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#991 use ActivePerl preset for building CE MSI installers
  .github/workflows/build.yml
  .github/workflows/integration-test.yml
Labels: version: patch

#993 substitute locale ids with their values
  pkg/platform/runtime/alternative.go
Labels: version: patch

#997 state init favours CWD
  internal/runners/initialize/init.go
  internal/runners/initialize/init_test.go
  internal/testhelpers/osutil/path_helpers_lin_mac.go
  internal/testhelpers/osutil/path_helpers_win.go
  locale/en-us.yaml
Labels: version: patch

#995 Track install type as custom dimension
  installers/msi-language/ActiveState/Rollbar.cs
  installers/msi-language/ActiveState/Tracker.cs
  installers/msi-language/Product.p.wxs
  installers/msi-language/StateDeploy/CustomAction.cs
Labels: version: patch

#996 Update default activestate.yaml
  internal/language/language.go
  internal/runners/activate/checkout.go
  internal/runners/packages/add.go
  internal/runners/packages/search.go
  internal/runners/packages/update.go
  locale/en-us.yaml
  pkg/platform/model/projects.go
  pkg/projectfile/projectfile.go
  test/integration/init_int_test.go
  test/integration/shared_int_test.go
Labels: version: patch

#998 Start prepare command
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/prepare.go
  internal/captain/command.go
  internal/captain/option.go
  internal/runners/prepare/prepare.go
Labels: version: minor

#1003 Make default project globally available
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
Labels: version: patch
