Repository ActiveState/cli, pull requests merged in 2020-11, with the labels that each got.

#1061 Fix cases where error is empty
  cmd/state/errors.go
Labels: version: patch

#1068 Fix forwarding durning update
  internal/updater/check.go
  internal/updater/updater.go
  test/integration/activate_int_test.go
  test/integration/package_int_test.go
Labels: run integration tests, run-int-test-only:update, version: patch

#1070 Turn on headless mode
  internal/runners/packages/packages.go
Labels: version: patch

#1071 Fix move files error
  internal/fileutils/fileutils.go
Labels: version: patch

#1072 Don't wait for panic recover if we know bufferInfo is nil
  internal/output/colorstyle/console_windows.go
Labels: version: patch

#1073 Remove install-source from environment info
  internal/logging/rollbar.go
Labels: version: patch

#1075 Ensure that we have the activation events necessary to measure success
  cmd/state/internal/cmdtree/activate.go
  internal/analytics/analytics.go
  internal/captain/command.go
  internal/errs/unwrap.go
  internal/runners/activate/activate.go
  internal/runners/activate/activation.go
  pkg/projectfile/projectfile.go
Labels: version: patch

#1076 add cmd line flag to filter for local projects only
  cmd/state/internal/cmdtree/projects.go
  internal/runners/projects/projects.go
  internal/runners/projects/projects_test.go
Labels: version: patch

#1052 Add before/after cmd event handling
  cmd/state/errors.go
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/intercepts/cmdcall/cmdcall.go
  internal/captain/command.go
  internal/events/cmdcall/cmdcall.go
  internal/locale/errors.go
  internal/runners/run/run.go
  internal/runners/run/run_with_args_test.go
  internal/scriptrun/scriptrun.go
  internal/scriptrun/scriptrun_test.go
  internal/scriptrun/testdata/printEnv/activestate.yaml
  locale/en-us.yaml
  pkg/project/events.go
  test/integration/events_int_test.go
Labels: run-int-test-only:events, version: patch

#1077 Ensure build_engine file exists after installation
  pkg/platform/runtime/installer.go
  pkg/platform/runtime/runtime.go
Labels: version: patch

#1079 Implement `state install` resume
  internal/runners/packages/install.go
  internal/runners/packages/packages.go
  locale/en-us.yaml
  pkg/platform/authentication/auth.go
  pkg/platform/model/checkpoints.go
  pkg/platform/model/vcs.go
  pkg/platform/runtime/runtime.go
Labels: run-int-test-only:activate, run-int-test-only:package, version: patch

#1080 check for existence of project for package operations
  internal/runners/fork/fork.go
  internal/runners/languages/install.go
  internal/runners/languages/languages.go
  internal/runners/packages/install.go
  internal/runners/packages/uninstall.go
  internal/runners/pull/pull.go
  internal/runners/revert/revert.go
  internal/runners/run/run.go
  internal/runners/scripts/edit.go
  internal/runners/scripts/scripts.go
  internal/runners/show/show.go
  internal/runners/update/update.go
  locale/en-us.yaml
Labels: version: patch

#1086 Remove pkg add integration test as the results are too unreliable for integration tests
  test/integration/push_int_test.go
Labels: run-int-test-only:push, version: patch

#1084 Add --activate-default flag to installer scripts
  installers/install.ps1
  installers/install.sh
Labels: version: patch

#1082 Fix panic when command has typo
  activestate.yaml
  internal/captain/command.go
Labels: version: patch

#1085 `state projects` is now local, and `state projects remote` is remote
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/projects.go
  internal/runners/projects/projects.go
  internal/runners/projects/projects_test.go
  internal/runners/projects/remote.go
  internal/sliceutils/sliceutils.go
  internal/sliceutils/sliceutils_test.go
  locale/en-us.yaml
  pkg/projectfile/projectfile.go
Labels: version: patch

#1091 Add tip to 'cannot activate activated' error
  internal/runners/activate/activate.go
Labels: version: patch

#1089 Installers overwrite with -f
  installers/install.ps1
  installers/install.sh
Labels: version: patch

#1090 Add default prompt
  activestate.yaml
  internal/runners/activate/activate.go
  internal/runners/activate/namespace.go
  internal/subshell/sscommon/rcfile.go
  internal/virtualenvironment/virtualenvironment.go
  locale/en-us.yaml
  test/integration/activate_int_test.go
  test/integration/push_int_test.go
Labels: version: patch

#1087 add state bundles command
  cmd/state/internal/cmdtree/bundles.go
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/packages.go
  internal/runners/packages/install.go
  internal/runners/packages/list.go
  internal/runners/packages/packages.go
  internal/runners/packages/search.go
  internal/runners/packages/uninstall.go
  internal/testhelpers/tagsuite/tagsuite.go
  locale/en-us.yaml
  pkg/platform/model/inventory.go
  pkg/platform/model/vcs.go
  test/integration/bundle_int_test.go
  test/integration/package_int_test.go
Labels: run integration tests, run-int-test-only:run, version: patch

#1083 Install.sh should not fail inside activated environment
  installers/install.ps1
  installers/install.sh
Labels: version: patch

#1095 Rephrase package removed
  locale/en-us.yaml
  test/integration/package_int_test.go
Labels: version: patch

#1092 Analytic events can now be deferred
  cmd/state/internal/cmdtree/shim.go
  internal/analytics/analytics.go
  internal/analytics/analytics_test.go
  internal/analytics/deferred.go
  internal/captain/command.go
Labels: version: patch

#1094 Fix shim error looking for projectfile
  internal/globaldefault/default.go
  internal/runners/activate/activation.go
  internal/runners/activate/namespace.go
  internal/runners/shim/shim.go
Labels: version: patch

#1093 wait for analytics calls to finish in background
  go.mod
  go.sum
  internal/analytics/analytics.go
  internal/analytics/analytics_test.go
  internal/analytics/deferred.go
  internal/captain/command.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: version: patch

#1097 State import supports headless state
  internal/runners/packages/import.go
  internal/testhelpers/tagsuite/tagsuite.go
  pkg/platform/model/vcs.go
  test/integration/import_int_test.go
Labels: run integration tests, run-int-test-only:import, version: patch

#1098 Strip color codes from JSON output
  internal/output/json.go
Labels: version: patch

#1096 Small styling changes
  cmd/state/errors.go
  cmd/state/main.go
  internal/colorize/colorize.go
  internal/runners/initialize/init.go
  internal/runners/push/push.go
  locale/en-us.yaml
Labels: version: patch

#1099 Hotfix - install.sh missing back tick
  installers/install.sh
  pkg/projectfile/projectfile.go
Labels: version: patch

#1100 Fix missing groups / redundant groups
  cmd/state/internal/cmdtree/bundles.go
  cmd/state/internal/cmdtree/revert.go
  cmd/state/internal/cmdtree/secrets.go
Labels: version: patch

#1102 Don't error out if dependencies already installed
  internal/runners/packages/packages.go
Labels: version: patch

#1104 Rewrite old path entries in installers
  installers/install.ps1
  installers/install.sh
Labels: version: patch

#1103 manage progress bar width based on terminal width
  internal/progress/_demo/main.go
  internal/progress/progress.go
Labels: version: patch

#1101 Fix activation after update
  internal/process/process.go
  internal/runners/activate/activate.go
  internal/runners/activate/activation.go
  internal/scriptrun/scriptrun.go
  internal/subshell/subshell.go
  internal/subshell/subshell_test.go
  scripts/unsupported/fupdstor/main.go
  scripts/unsupported/fupdstor/setmod-by-hrs
Labels: version: patch

#1107 Change logging level for terminal size error
  internal/progress/progress.go
Labels: version: patch

#1106 Install scripts activate project even if state tool is installed
  installers/install.ps1
  installers/install.sh
Labels: version: patch

#1110 Update prompt color on Windows
  internal/prompt/helpers.go
Labels: version: patch

#1105 Add permissions context to error
  internal/runners/languages/install.go
  pkg/platform/model/vcs.go
Labels: version: patch

#1108 Ignore ExitCode error during state activate
  cmd/state/errors.go
  internal/errs/unwrap.go
  internal/failures/failures.go
  internal/runners/activate/activation.go
  internal/subshell/bash/bash.go
  internal/subshell/cmd/cmd.go
  internal/subshell/fish/fish.go
  internal/subshell/sscommon/sscommon.go
  internal/subshell/subshell.go
  internal/subshell/tcsh/tcsh.go
  internal/subshell/zsh/zsh.go
  internal/testhelpers/tagsuite/tagsuite.go
  test/integration/activate_int_test.go
  test/integration/run_int_test.go
Labels: run integration tests, run-int-test-only:exit-code, version: patch

#1111 Return if there is no parent process
  internal/process/process.go
Labels: version: patch

#1112 pick first platformID if more than one is available
  locale/en-us.yaml
  pkg/platform/model/recipe.go
Labels: version: patch

#1113 Headless projects "match" namespace
  internal/runners/activate/namespace.go
Labels: version: patch

#1116 Fixing install.sh one-liner
  installers/install.sh
Labels: version: patch

#1114 install scripts: de-activate some instruction messages on activation
  installers/install.sh
  internal/runners/prepare/prepare.go
  locale/en-us.yaml
Labels: run integration tests, run-int-test-only:prepare, version: patch

#1115 State search UX
  internal/runners/packages/search.go
  internal/runners/packages/table.go
  locale/en-us.yaml
  test/integration/package_int_test.go
Labels: run integration tests, run-int-test-only:package, version: patch

#1117 State history uses commit ID from as.yaml
  cmd/state/internal/cmdtree/history.go
  internal/runners/history/history.go
  pkg/platform/model/vcs.go
  test/integration/history_int_test.go
Labels: run integration tests, run-int-test-only:history, version: patch

#1119 Install.sh needs to work in bash
  .github/workflows-src/jobs.lib.yml
  .github/workflows/build.yml
  .github/workflows/integration-test.yml
  installers/install.sh
Labels: version: patch

#1118 add a global signal handler for interrupts
  cmd/state/internal/cmdtree/activate.go
  internal/captain/command.go
  internal/runners/activate/activation.go
  internal/sighandler/awaiting.go
  internal/sighandler/background.go
  internal/sighandler/sighandler.go
  internal/sighandler/sighandler_test.go
  internal/subshell/sscommon/sscommon.go
  internal/subshell/subshell_lin_mac_test.go
  internal/subshell/subshell_win_test.go
Labels: version: patch

#1121 Allow for case-insensitive package names
  internal/testhelpers/e2e/session.go
  pkg/platform/model/inventory.go
  pkg/platform/model/inventory_test.go
  pkg/projectfile/projectfile.go
  test/integration/push_int_test.go
Labels: run integration tests, run-int-test-only:package, version: patch

#1123 State history does not require authentication on public projects
  internal/runners/history/history.go
  pkg/platform/model/vcs.go
Labels: run integration tests, run-int-test-only:history, version: patch

#1122 Silence shim errors
  cmd/state/errors.go
  internal/errs/errs.go
Labels: version: patch

#1081 Table output
  go.mod
  internal/output/plain.go
  internal/output/plain_test.go
  internal/runbits/invoke.go
  internal/runners/events/events.go
  internal/runners/projects/projects.go
  internal/runners/projects/remote.go
  internal/sliceutils/sliceutils.go
  internal/sliceutils/sliceutils_test.go
  internal/table/table.go
  internal/table/table_test.go
  internal/termutils/termutils.go
Labels: version: patch

#1125 Make case-insenstive install work without versions
  pkg/platform/model/inventory.go
Labels: version: patch

#1124 Send GA events on confirm prompts
  internal/analytics/analytics.go
  internal/prompt/prompt.go
Labels: version: patch

#1127 write instructions to disable auto-update prior to updating
  internal/runners/update/update.go
  internal/updater/check.go
  internal/updater/updater.go
  internal/updater/updater_lin_mac_test.go
  internal/updater/updater_test.go
  locale/en-us.yaml
Labels: version: patch

#1128 Ensure verbose flag is working
  cmd/state/main.go
  internal/logging/defaults.go
Labels: version: patch

#1126 state push can push to existing projects
  cmd/state/internal/cmdtree/push.go
  internal/fileutils/fileutils.go
  internal/runners/push/push.go
  pkg/projectfile/projectfile.go
  test/integration/push_int_test.go
Labels: run integration tests, run-int-test-only:init, run-int-test-only:push, version: patch

#1129 Powershell intstaller encoding
  installers/install.ps1
Labels: version: patch

#1130 explain and fix admin default installations
  assets/.gitattributes
  internal/globaldefault/default.go
  internal/subshell/cmd/cmd.go
  internal/subshell/cmd/env.go
  internal/subshell/cmd/env_test.go
Labels: version: patch

#1138 Fix space handling in ps1 installer
  installers/install.ps1
Labels: version: patch

#1135 Auth error newline
  pkg/platform/authentication/auth.go
Labels: version: patch

#1134 skip rollbar for local builds
  internal/logging/defaults.go
Labels: version: patch

#1133 Update commit printing
  internal/runners/history/history.go
  internal/table/table.go
  internal/table/table_test.go
  locale/en-us.yaml
  pkg/cmdlets/commit/commit.go
Labels: run integration tests, run-int-test-only:history, version: patch

#1139 Return error from projects remote runner
  internal/runners/projects/remote.go
Labels: version: patch

#1140 Fix projects runner tests
  internal/runners/projects/projects_test.go
Labels: version: patch

#1142 Add warning for administrator users
  internal/globaldefault/default.go
  internal/runners/activate/activate.go
Labels: version: patch
