Repository ActiveState/cli, pull requests merged in 2020-12, with the labels that each got.

#1146 case insenstive activation
  pkg/cmdlets/git/git.go
  pkg/platform/api/graphql/request/project.go
  test/integration/activate_int_test.go
Labels: run integration tests, run-int-test-only:activate, version: patch

#1147 Handle lack of commitid in languages listing runner
  internal/runners/languages/languages.go
  locale/en-us.yaml
  test/integration/languages_int_test.go
Labels: version: patch

#1144 Populate anonID field on headless commits
  internal/analytics/analytics.go
  internal/logging/rollbar.go
  internal/machineid/machineid.go
  internal/machineid/machineid_test.go
  internal/runners/activate/checkout.go
  internal/runners/history/history.go
  internal/runners/history/history_test.go
  internal/runners/packages/import.go
  internal/runners/packages/packages.go
  internal/runners/revert/revert.go
  pkg/cmdlets/commit/commit.go
  pkg/cmdlets/git/git.go
  pkg/cmdlets/git/git_test.go
  pkg/cmdlets/git/mock/mock.go
  pkg/platform/api/api.go
  pkg/platform/api/graphql/graphql.go
  pkg/platform/api/graphql/model/projectconv.go
  pkg/platform/api/mono/mono_models/commit.go
  pkg/platform/api/mono/mono_models/commit_editable.go
  pkg/platform/api/mono/mono_models/project.go
  pkg/platform/api/mono/mono_models/project_editable.go
  pkg/platform/authentication/auth.go
  pkg/platform/model/vcs.go
Labels: version: patch

#1148 Clean up table math to improve maintainability
  internal/mathutils/mathutils.go
  internal/mathutils/mathutils_test.go
  internal/output/plain_test.go
  internal/sliceutils/sliceutils.go
  internal/sliceutils/sliceutils_test.go
  internal/table/table.go
  internal/table/table_test.go
Labels: version: patch

#1149 Use ResolveRecipes instead of SolveOrder
  pkg/platform/model/recipe.go
  pkg/platform/runtime/download.go
Labels: version: patch

#1150 add integration test for install.ps1
  .github/workflows-src/steps.lib.yml
  .github/workflows/build.yml
  installers/install.ps1
  test/integration/install_scripts_int_test.go
Labels: version: patch

#1143 Get auth status from scripts
  cmd/state/main.go
  internal/constraints/constraints.go
  pkg/project/expander.go
  test/integration/condition_int_test.go
Labels: run integration tests, run-int-test-only:condition, version: patch

#1151 Add matching features list to pkgs search output
  internal/output/plain.go
  internal/runners/packages/search.go
  test/integration/package_int_test.go
  vendor/github.com/Netflix/go-expect/go.mod
  vendor/github.com/Netflix/go-expect/go.sum
  vendor/gopkg.in/yaml.v3/go.mod
Labels: version: patch

#1153 Fix bug in WriteRcFile
  internal/subshell/sscommon/rcfile.go
  internal/subshell/sscommon/rcfile_test.go
Labels: version: patch

#1154 Add install.sh integration test
  test/integration/install_scripts_int_test.go
Labels: version: patch

#1155 Do not prepare global binary directory twice
  internal/globaldefault/default.go
  test/integration/prepare_int_test.go
Labels: version: patch

#1156 remove environment backup logic
  internal/subshell/cmd/env.go
  internal/subshell/cmd/env_test.go
  test/integration/install_scripts_int_test.go
Labels: version: patch

#1157 Handle more of the potential pflag errors in captain
  internal/captain/command.go
  locale/en-us.yaml
Labels: version: patch

#1159 Revert Allow for case-insensitive package names
  internal/testhelpers/e2e/session.go
  pkg/platform/model/inventory.go
  pkg/projectfile/projectfile.go
Labels: version: patch

#1158 Clean up crop and renderRow logic
  internal/colorize/cropped.go
  internal/colorize/cropped_test.go
  internal/table/table.go
Labels: version: patch

#1152 Table word wrapping handles colour codes
  internal/colorize/cropped.go
  internal/colorize/cropped_test.go
  internal/table/table.go
  internal/table/table_test.go
Labels: version: patch

#1160 Add Simple outputter
  internal/output/output.go
  internal/output/plain.go
  internal/output/simple.go
  internal/output/simple_test.go
Labels: version: patch

#1162 Handle invalid semantic version values
  internal/language/language.go
  internal/language/language_test.go
Labels: version: patch

#1163 Add vertical table handling
  internal/output/plain.go
  internal/output/plain_test.go
  internal/table/table.go
  internal/table/table_test.go
Labels: version: patch

#1164 add non-interactive prompt flag
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/main.go
  cmd/state/main_test.go
  cmd/state/output.go
  internal/prompt/cmd/test.go
  internal/prompt/helpers_test.go
  internal/prompt/mock/mock.go
  internal/prompt/prompt.go
  internal/runners/packages/import.go
  internal/runners/scripts/edit.go
  internal/runners/scripts/edit_test.go
  internal/runners/scripts/scripts.go
  internal/runners/secrets/secrets.go
  internal/runners/update/update.go
  internal/runners/update/update_test.go
  internal/scriptrun/scriptrun_test.go
  locale/en-us.yaml
  pkg/project/expander.go
  pkg/project/project.go
  pkg/project/prompting_expander_test.go
  pkg/project/secrets.go
  pkg/project/secrets_access_test.go
Labels: version: patch

#1165 Update state history UX
  internal/runners/history/history.go
  locale/en-us.yaml
  pkg/cmdlets/commit/commit.go
Labels: version: patch

#1167 State install presents alternatives
  internal/runners/packages/packages.go
  locale/en-us.yaml
  pkg/platform/model/inventory.go
Labels: version: patch

#1161 update UX for `state show`
  internal/runners/packages/table.go
  internal/runners/show/show.go
  test/integration/show_int_test.go
Labels: run integration tests, run-int-test-only:show, version: patch

#1168 Clean up deps
  go.mod
  go.sum
  vendor/github.com/autarch/testify/mock/doc.go
  vendor/github.com/autarch/testify/mock/mock.go
  vendor/github.com/autarch/testify/require/doc.go
  vendor/github.com/autarch/testify/require/forward_requirements.go
  vendor/github.com/autarch/testify/require/require.go
  vendor/github.com/autarch/testify/require/require.go.tmpl
  vendor/github.com/autarch/testify/require/require_forward.go
  vendor/github.com/autarch/testify/require/require_forward.go.tmpl
  vendor/github.com/autarch/testify/require/requirements.go
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/testify/.github/pull_request_template.md
  vendor/github.com/stretchr/testify/.gitignore
  vendor/github.com/stretchr/testify/.travis.gofmt.sh
  vendor/github.com/stretchr/testify/.travis.gogenerate.sh
  vendor/github.com/stretchr/testify/.travis.govet.sh
  vendor/github.com/stretchr/testify/.travis.yml
  vendor/github.com/stretchr/testify/CONTRIBUTING.md
  vendor/github.com/stretchr/testify/MAINTAINERS.md
  vendor/github.com/stretchr/testify/README.md
  vendor/github.com/stretchr/testify/assert/assertion_compare_test.go
  vendor/github.com/stretchr/testify/assert/assertion_order_test.go
  vendor/github.com/stretchr/testify/assert/assertions_test.go
  vendor/github.com/stretchr/testify/assert/forward_assertions_test.go
  vendor/github.com/stretchr/testify/assert/http_assertions_test.go
  vendor/github.com/stretchr/testify/doc.go
  vendor/github.com/stretchr/testify/go.mod
  vendor/github.com/stretchr/testify/go.sum
  vendor/github.com/stretchr/testify/http/doc.go
  vendor/github.com/stretchr/testify/http/test_response_writer.go
  vendor/github.com/stretchr/testify/http/test_round_tripper.go
  vendor/github.com/stretchr/testify/mock/mock_test.go
  vendor/github.com/stretchr/testify/package_test.go
  vendor/github.com/stretchr/testify/require/forward_requirements_test.go
  vendor/github.com/stretchr/testify/require/requirements_test.go
  vendor/github.com/stretchr/testify/suite/stats_test.go
  vendor/github.com/stretchr/testify/suite/suite_test.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/modules.txt
Labels: version: patch

#1169 fix scriptrun not sourcing environment on CI
  test/integration/push_int_test.go
Labels: version: patch

#1171 Restrict table col equalization to max width tables
  internal/output/plain_test.go
  internal/table/table.go
Labels: version: patch

#1173 expand jwt token in scripts
  pkg/project/expander.go
Labels: version: patch

#1170 replace validation for package installation
  internal/runners/packages/packages.go
  locale/en-us.yaml
  pkg/platform/model/inventory.go
  pkg/platform/model/recipe.go
  test/integration/bundle_int_test.go
  test/integration/package_int_test.go
  test/integration/push_int_test.go
Labels: run integration tests, run-int-test-only:package, version: patch

#1174 Deploy on master, beta and release
  .github/workflows-src/steps.lib.yml
  .github/workflows/build.yml
Labels: version: patch

#1175 use version.txt to set version
  .github/workflows-src/jobs.lib.yml
  .github/workflows-src/steps.lib.yml
  .github/workflows/build.yml
  .github/workflows/integration-test.yml
  cmd/state/main_test.go
  internal/constants/preprocess/github.go
  internal/constants/preprocess/github_test.go
  internal/constants/preprocess/preprocess.go
  internal/constants/version/version.go
  internal/constants/version/version_test.go
  version.txt
Labels: version: patch

#1176 Build on release and beta branches
  .github/workflows-src/build.yml
  .github/workflows/build.yml
Labels: version: patch

#1172 Start info command
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/packages.go
  internal/errs/errs.go
  internal/runners/packages/info.go
  locale/en-us.yaml
  pkg/platform/model/inventory.go
  test/integration/package_int_test.go
Labels: version: minor

#1186 Ensure clean uninstall cmd removes all config files
  internal/config/config.go
  internal/config/instance.go
  internal/runners/clean/run_lin_mac.go
  internal/runners/clean/run_win.go
Labels: version: patch

#1181 Add --set-channel flag and move `update --lock` to `lock` subcommand
  cmd/state/internal/cmdtree/cmdtree.go
  cmd/state/internal/cmdtree/update.go
  internal/runners/update/lock.go
  internal/runners/update/update.go
  internal/runners/update/update_test.go
  internal/updater/updater.go
  locale/en-us.yaml
  pkg/project/project.go
  pkg/project/project_test.go
  pkg/project/testdata/activestate.yaml
  pkg/projectfile/projectfile.go
  pkg/projectfile/projectfile_test.go
  test/integration/update_int_test.go
Labels: run integration tests, run-int-test-only:update
